### ISSUE TITLE
[k8s] configurable provider

### ISSUE THREAD

**Issue by ritazh** [Azure/container-compute-upstream#27]
let's get rid of azure.json and use configmaps instead

**Comment by feiskyer** [comment]
Actually, secret should be used. As there are credentials within azure.json and we don't actually support update the config.json dynamically.

**Comment by ritazh** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/77309

**Comment by khenidak** [comment]
Here is a proposed plan, I am not sure if we need to have this as KEP. if so i can move it to KEP

## Why are we doing this?
Users should be able to change the configuration of the `control-plane` without having to edit every machine manually. Today, even if they edit the machine manually the settings they have gets overridden with whatever `arm` has in `CSE` and `cloud-init`, making the entire experience extremely painful. The rest of control plane currently is configurable via component config approach. AKS-engine is already queueing the work to move away from command line parameters to component config. 

## Limitation and Key Principals
1. We will not support dynamic reconfiguration of cloud provider. The reconfiguration will be done via **restarting** the host of the cloud provider kubelet, cm etc.
2.  We need to support backward compat across existing and new clusters. 
3. The cloud provider initiation sequence is spread over two funcs [NewCloud() func ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L230) which is registered with cloud provider package's [init() func] (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L225) and cloud provider interface own [Initialize() func](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L455). The biggest hurdle is `initialize()` is the function that gets a `clientset` instance and does not return `error`. In other words, failures in `initialize()` will not trigger failure to the host of cloud provider. I am already in talks with cloud provider sig on this. 
4. The below approach has dependency on `authMode == none` as described by https://github.com/kubernetes/kubernetes/issues/77309.
5. We will not support partial configuration override (parts in azure.json and parts in secret), the secret config must contain all the new values.


## Approach

1. The cloud provider will initialize **completely** using `NewCloud()` as is today. Specially things that can generate an error, such as [cache initiation](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L405).
2. The `Initialize()` func will be updated to look for a well-known *please read below on overriding config* `secret`. The `secret` is a serialized version of azure.json file. The cloud provider will re-initialize using the values from the secret instead of azure.json file according to overriding config rules below.

## Changes to configuration type
1. Add new field named `configType` that contains the values `all`, `node` or `control-plane`. The idea is tell cloud provider if it should configure itself as either. the **default** value is `all` meaning: the secret will apply on all components.
2. Add new field named `overrideType` that contains the values 
- `no-override`: The cloud provider configuration **must not** be overridden by whatever in the secret.
- `must-override`: the cloud provider configuration **must** be overridden by a secret. 
- `can-override`: the cloud provider configuration **can be optionally** overridden by a secret, this is **default** value.

### configuration Override Workflow
1. User create a cluster normally as-is today. Or with secrets as static manifest loaded by kubelet on masters. User can create secrets with the following name
`<well-known-prefix>`: to configure **all** components of the system.
`<well-known-prefix>-control-plane`: To configure control plane components
`<well-known-prefix>-node`: to configure nodes
`<well-known-prefix>-node-<node-name>`: to configure a specific node (used for flighting and configuration testing.
2. the secrets are all created in `azure-system` with limited rbac access.
3. When `InitializeI()` is called:
  a. Step 1: Secret name 
      - If the value of azure.json (henceforth is called file) `file.configType == all` the resulting secret name is `<well-known-prefix>`
     - If the value of `file.ConfigType==node` the resulting secret name is `<well-known-prefix>-node`
     - If the value of `file.ConfigType==control-plane` the resulting secret name is `<well-known-prefix>-control-plane`
  b. Step 2: Overriding
      - If `file.overrideType == none` Initialize() func will return and no further processing needed.
      - If  `file.overrideType == must-override` then we need to try and retry to get the secret. Note in new clusters situation the secret may not be there yet (because of race condition between cloud provider host and kubelet on master) before we fail and log that `config override` has failed, we also need to put the state of the cloud provider in error state (maybe nulling all interfaces we return from `Instances()` or `Zones()` etc..
      - If `file.overrideType == can-override` then we try if we got `404` then we use what was originally in azure.json
  c. Step 3: Handling `named node` configuration. If the value of `file.ConfigType==node` then we need to look for secret named `<well-known-prefix>-node-<node-name>` if the result is `404` then we fall back to `<well-known-prefix>-node` (please keep in mind the race condition detailed above).

### Handling failures
if we failed to parse or find the secret && `file.overrideType == must-override` then we need to put the entire cloud provider in failure state (please keep in mind that `Initialize()` func does not return error) .

## Impact on existing clusters.
By default all existing clusters will have `file.overrideType == can-override`  (review default values above). Users will use the generalized configuration approach, however they can selectively start applying named/typed configuration as needed.


> Note, eventually we need to version our configuration. While it is not mandatory at this stage, i believe doing it as part of the above work will make our life a lot easier in the future

**Comment by jackfrancis** [comment]
How long will we support the "check for secrets first then fall back to azure.json" approach?

I would argue that once we stabilize the new paradigm we should quickly remove support for `azure.json` entirely. We might want to do some discovery work to uncover non-AKS Engine toolchains that are manually scaffolding azure.json Azure cloudprovider specs, and notify them that they will have to update to the new paradigm.

**Comment by khenidak** [comment]
Yes and yes. We should move away, Once the above is merged and stable (and we covered all the weird edge cases) let us declare azure.json as deprecated across all repos. I believe deprecation is 2 (or was it 3?) releases before we error on it.

**Comment by feiskyer** [comment]
See https://github.com/kubernetes/kubernetes/pull/78242

**Comment by justaugustus** [comment]
> Here is a proposed plan, I am not sure if we need to have this as KEP. if so i can move it to KEP

@khenidak -- Yes, this will need to be a KEP and an enhancement tracking issue in k/enhancements. Let's get one in place as soon as we can, so we can start to discuss [deprecation](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior) of the azure.json config.

cc: @andrewsykim

**Comment by feiskyer** [comment]
Added by https://github.com/kubernetes/kubernetes/pull/78242. Would start the KEP for azure.json deprecation in 1.16 release cycle.

**Comment by feiskyer** [comment]
configmap already supported.
